<script lang="ts" setup>
import { ref } from 'vue'
import NavTab from '@/components/atoms/NavTab.vue'

// state
const selectedRevType = ref('Yours')
const revenueData = {
  yours: {
    current: {
      usd: 4251.24,
      crypto: [
        {denom: 'ETH', amount: 0.53},
        {denom: 'USDC', amount: 2421.55},
        {denom: 'MATIC', amount: 123.53},
      ]
    },
    toDate: {
      usd: 4251.24,
      crypto: [
        {denom: 'ETH', amount: 0.53},
        {denom: 'USDC', amount: 2421.55},
        {denom: 'MATIC', amount: 123.53},
      ]
    }
  },
  total: {
    toDate: {
      usd: 244251.24,
      crypto: [
        {denom: 'ETH', amount: 12.53},
        {denom: 'USDC', amount: 53523.23},
        {denom: 'MATIC', amount: 4215.22},
        {denom: 'WBTC', amount: 0.02},
      ]
    }
  }
}

</script>

<template>
  <div class="text-center">
    <h4 class="mb-2">Your tokens</h4>
    <p class="mb-2">2,378.03 gTES</p>
    <button
      title="Approve"
      class="btn-white inline-block px-4 py-1 min-w-[7rem]"
    >
      Trade 🡕
    </button>
    <h4 class="mt-8 mb-2">Revenue</h4>
    <small class="text-grey3">Generated by sponsored posts and tips commission (20%)</small>
    <div class="max-w-screen-md mx-auto mb-4 mt-4 text-center flex-center">
      <NavTab
        v-for="revType in ['Yours', 'Total']"
        :text="revType"
        :selected="revType === selectedRevType"
        @click="selectedRevType = revType"
      />
    </div>
    <div v-if="selectedRevType === 'Yours'">
      <h5>- Current -</h5>
      <strong>{{ revenueData.yours.current.usd }} USD</strong>
      <p
        v-for="token in revenueData.yours.current.crypto"
      >
        {{ token.amount }} {{ token.denom }}
      </p>
      <button
        title="Pay out"
        class="btn-white inline-block px-4 py-1 mt-2 mb-6 min-w-[7rem]"
      >
        Pay out
      </button>
    </div>
    <h5>- To date -</h5>
    <strong>{{ revenueData[selectedRevType.toLowerCase()].toDate.usd }} USD</strong>
    <p
      v-for="token in revenueData[selectedRevType.toLowerCase()].toDate.crypto"
    >
      {{ token.amount }} {{ token.denom }}
    </p>
  </div>
</template>
